[package]
name = "reimu"
version = "0.1.0"
edition = "2024"

[dependencies]
elf = "0.8.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
clap = { version = "4.5.49", features = ["cargo"] }
cpp_demangle = "0.5.0"
